// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: internal/proto/arena/arena.proto

package arenapb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayMoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         []string               `protobuf:"bytes,1,rep,name=board,proto3" json:"board,omitempty"`
	Position      int32                  `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	HumanMark     string                 `protobuf:"bytes,3,opt,name=human_mark,json=humanMark,proto3" json:"human_mark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayMoveRequest) Reset() {
	*x = PlayMoveRequest{}
	mi := &file_internal_proto_arena_arena_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayMoveRequest) ProtoMessage() {}

func (x *PlayMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_arena_arena_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayMoveRequest.ProtoReflect.Descriptor instead.
func (*PlayMoveRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_arena_arena_proto_rawDescGZIP(), []int{0}
}

func (x *PlayMoveRequest) GetBoard() []string {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *PlayMoveRequest) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *PlayMoveRequest) GetHumanMark() string {
	if x != nil {
		return x.HumanMark
	}
	return ""
}

type PlayMoveResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Board              []string               `protobuf:"bytes,1,rep,name=board,proto3" json:"board,omitempty"`
	BotPosition        int32                  `protobuf:"varint,2,opt,name=bot_position,json=botPosition,proto3" json:"bot_position,omitempty"`
	Outcome            string                 `protobuf:"bytes,3,opt,name=outcome,proto3" json:"outcome,omitempty"`
	Strategy           string                 `protobuf:"bytes,4,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Score              int32                  `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`
	NodesEvaluated     int32                  `protobuf:"varint,6,opt,name=nodes_evaluated,json=nodesEvaluated,proto3" json:"nodes_evaluated,omitempty"`
	SearchDepth        int32                  `protobuf:"varint,7,opt,name=search_depth,json=searchDepth,proto3" json:"search_depth,omitempty"`
	DecisionTimeMicros int64                  `protobuf:"varint,8,opt,name=decision_time_micros,json=decisionTimeMicros,proto3" json:"decision_time_micros,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PlayMoveResponse) Reset() {
	*x = PlayMoveResponse{}
	mi := &file_internal_proto_arena_arena_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayMoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayMoveResponse) ProtoMessage() {}

func (x *PlayMoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_arena_arena_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayMoveResponse.ProtoReflect.Descriptor instead.
func (*PlayMoveResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_arena_arena_proto_rawDescGZIP(), []int{1}
}

func (x *PlayMoveResponse) GetBoard() []string {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *PlayMoveResponse) GetBotPosition() int32 {
	if x != nil {
		return x.BotPosition
	}
	return 0
}

func (x *PlayMoveResponse) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *PlayMoveResponse) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *PlayMoveResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *PlayMoveResponse) GetNodesEvaluated() int32 {
	if x != nil {
		return x.NodesEvaluated
	}
	return 0
}

func (x *PlayMoveResponse) GetSearchDepth() int32 {
	if x != nil {
		return x.SearchDepth
	}
	return 0
}

func (x *PlayMoveResponse) GetDecisionTimeMicros() int64 {
	if x != nil {
		return x.DecisionTimeMicros
	}
	return 0
}

var File_internal_proto_arena_arena_proto protoreflect.FileDescriptor

const file_internal_proto_arena_arena_proto_rawDesc = "" +
	"\n" +
	" internal/proto/arena/arena.proto\x12\x05arena\"b\n" +
	"\x0fPlayMoveRequest\x12\x14\n" +
	"\x05board\x18\x01 \x03(\tR\x05board\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x05R\bposition\x12\x1d\n" +
	"\n" +
	"human_mark\x18\x03 \x01(\tR\thumanMark\"\x95\x02\n" +
	"\x10PlayMoveResponse\x12\x14\n" +
	"\x05board\x18\x01 \x03(\tR\x05board\x12!\n" +
	"\fbot_position\x18\x02 \x01(\x05R\vbotPosition\x12\x18\n" +
	"\aoutcome\x18\x03 \x01(\tR\aoutcome\x12\x1a\n" +
	"\bstrategy\x18\x04 \x01(\tR\bstrategy\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x05R\x05score\x12'\n" +
	"\x0fnodes_evaluated\x18\x06 \x01(\x05R\x0enodesEvaluated\x12!\n" +
	"\fsearch_depth\x18\a \x01(\x05R\vsearchDepth\x120\n" +
	"\x14decision_time_micros\x18\b \x01(\x03R\x12decisionTimeMicros2D\n" +
	"\x05Arena\x12;\n" +
	"\bPlayMove\x12\x16.arena.PlayMoveRequest\x1a\x17.arena.PlayMoveResponseB*Z(vibrox-core/internal/proto/arena;arenapbb\x06proto3"

var (
	file_internal_proto_arena_arena_proto_rawDescOnce sync.Once
	file_internal_proto_arena_arena_proto_rawDescData []byte
)

func file_internal_proto_arena_arena_proto_rawDescGZIP() []byte {
	file_internal_proto_arena_arena_proto_rawDescOnce.Do(func() {
		file_internal_proto_arena_arena_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_arena_arena_proto_rawDesc), len(file_internal_proto_arena_arena_proto_rawDesc)))
	})
	return file_internal_proto_arena_arena_proto_rawDescData
}

var file_internal_proto_arena_arena_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_arena_arena_proto_goTypes = []any{
	(*PlayMoveRequest)(nil),  // 0: arena.PlayMoveRequest
	(*PlayMoveResponse)(nil), // 1: arena.PlayMoveResponse
}
var file_internal_proto_arena_arena_proto_depIdxs = []int32{
	0, // 0: arena.Arena.PlayMove:input_type -> arena.PlayMoveRequest
	1, // 1: arena.Arena.PlayMove:output_type -> arena.PlayMoveResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_arena_arena_proto_init() }
func file_internal_proto_arena_arena_proto_init() {
	if File_internal_proto_arena_arena_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_arena_arena_proto_rawDesc), len(file_internal_proto_arena_arena_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_arena_arena_proto_goTypes,
		DependencyIndexes: file_internal_proto_arena_arena_proto_depIdxs,
		MessageInfos:      file_internal_proto_arena_arena_proto_msgTypes,
	}.Build()
	File_internal_proto_arena_arena_proto = out.File
	file_internal_proto_arena_arena_proto_goTypes = nil
	file_internal_proto_arena_arena_proto_depIdxs = nil
}
