// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: internal/proto/arena/arena.proto

package arenapb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Arena_PlayMove_FullMethodName = "/arena.Arena/PlayMove"
)

// ArenaClient is the client API for Arena service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArenaClient interface {
	PlayMove(ctx context.Context, in *PlayMoveRequest, opts ...grpc.CallOption) (*PlayMoveResponse, error)
}

type arenaClient struct {
	cc grpc.ClientConnInterface
}

func NewArenaClient(cc grpc.ClientConnInterface) ArenaClient {
	return &arenaClient{cc}
}

func (c *arenaClient) PlayMove(ctx context.Context, in *PlayMoveRequest, opts ...grpc.CallOption) (*PlayMoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayMoveResponse)
	err := c.cc.Invoke(ctx, Arena_PlayMove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArenaServer is the server API for Arena service.
// All implementations must embed UnimplementedArenaServer
// for forward compatibility.
type ArenaServer interface {
	PlayMove(context.Context, *PlayMoveRequest) (*PlayMoveResponse, error)
	mustEmbedUnimplementedArenaServer()
}

// UnimplementedArenaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArenaServer struct{}

func (UnimplementedArenaServer) PlayMove(context.Context, *PlayMoveRequest) (*PlayMoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlayMove not implemented")
}
func (UnimplementedArenaServer) mustEmbedUnimplementedArenaServer() {}
func (UnimplementedArenaServer) testEmbeddedByValue()               {}

// UnsafeArenaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArenaServer will
// result in compilation errors.
type UnsafeArenaServer interface {
	mustEmbedUnimplementedArenaServer()
}

func RegisterArenaServer(s grpc.ServiceRegistrar, srv ArenaServer) {
	// If the following call pancis, it indicates UnimplementedArenaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Arena_ServiceDesc, srv)
}

func _Arena_PlayMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayMoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArenaServer).PlayMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Arena_PlayMove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArenaServer).PlayMove(ctx, req.(*PlayMoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Arena_ServiceDesc is the grpc.ServiceDesc for Arena service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Arena_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arena.Arena",
	HandlerType: (*ArenaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlayMove",
			Handler:    _Arena_PlayMove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/arena/arena.proto",
}
